In [58]:
import spacy
from nltk import sent_tokenize

In [33]:
!python -m spacy download en_core_web_trf

Collecting en-core-web-trf==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl (457.4 MB)
     ---------------------------------------- 0.0/457.4 MB ? eta -:--:--
     ---------------------------------------- 1.3/457.4 MB 9.6 MB/s eta 0:00:48
     --------------------------------------- 3.7/457.4 MB 10.9 MB/s eta 0:00:42
      -------------------------------------- 6.3/457.4 MB 11.4 MB/s eta 0:00:40
      -------------------------------------- 8.7/457.4 MB 11.7 MB/s eta 0:00:39
      ------------------------------------- 11.3/457.4 MB 11.6 MB/s eta 0:00:39
     - ------------------------------------ 13.6/457.4 MB 11.7 MB/s eta 0:00:38
     - ------------------------------------ 16.0/457.4 MB 11.4 MB/s eta 0:00:39
     - ------------------------------------ 17.8/457.4 MB 11.2 MB/s eta 0:00:40
     - ------------------------------------ 20.2/457.4 MB 11.3 MB/s eta 0:00:39
     - ------------------------------------ 22.8/457.4 MB 11.4 MB/s eta 0:00:39
     -- ----------------------------------- 25.2/457.4 MB 11.4 MB/s eta 0:00:38
     -- ----------------------------------- 27.8/457.4 MB 11.4 MB/s eta 0:00:38
     -- ----------------------------------- 30.4/457.4 MB 11.5 MB/s eta 0:00:38
     -- ----------------------------------- 33.0/457.4 MB 11.5 MB/s eta 0:00:37
     -- ----------------------------------- 35.4/457.4 MB 11.5 MB/s eta 0:00:37
     --- ---------------------------------- 37.7/457.4 MB 11.5 MB/s eta 0:00:37
     --- ---------------------------------- 39.8/457.4 MB 11.6 MB/s eta 0:00:37
     --- ---------------------------------- 42.2/457.4 MB 11.4 MB/s eta 0:00:37
     --- ---------------------------------- 44.8/457.4 MB 11.5 MB/s eta 0:00:37
     ---- --------------------------------- 48.2/457.4 MB 10.8 MB/s eta 0:00:38
     ---- --------------------------------- 50.9/457.4 MB 10.9 MB/s eta 0:00:38
     ---- --------------------------------- 53.2/457.4 MB 10.9 MB/s eta 0:00:37
     ---- --------------------------------- 55.8/457.4 MB 11.0 MB/s eta 0:00:37
     ---- --------------------------------- 58.5/457.4 MB 11.0 MB/s eta 0:00:37
     ----- -------------------------------- 61.1/457.4 MB 11.0 MB/s eta 0:00:36
     ----- -------------------------------- 63.7/457.4 MB 11.1 MB/s eta 0:00:36
     ----- -------------------------------- 66.3/457.4 MB 11.1 MB/s eta 0:00:36
     ----- -------------------------------- 68.7/457.4 MB 11.1 MB/s eta 0:00:35
     ----- -------------------------------- 71.0/457.4 MB 11.1 MB/s eta 0:00:35
     ------ ------------------------------- 73.7/457.4 MB 11.1 MB/s eta 0:00:35
     ------ ------------------------------- 75.5/457.4 MB 11.1 MB/s eta 0:00:35
     ------ ------------------------------- 78.6/457.4 MB 11.2 MB/s eta 0:00:34
     ------ ------------------------------- 81.3/457.4 MB 11.2 MB/s eta 0:00:34
     ------ ------------------------------- 83.9/457.4 MB 11.2 MB/s eta 0:00:34
     ------- ------------------------------ 86.0/457.4 MB 11.2 MB/s eta 0:00:34
     ------- ------------------------------ 87.8/457.4 MB 11.1 MB/s eta 0:00:34
     ------- ------------------------------ 90.2/457.4 MB 11.1 MB/s eta 0:00:34
     ------- ------------------------------ 92.8/457.4 MB 11.1 MB/s eta 0:00:33
     ------- ------------------------------ 95.2/457.4 MB 11.1 MB/s eta 0:00:33
     -------- ----------------------------- 97.5/457.4 MB 11.1 MB/s eta 0:00:33
     -------- ----------------------------- 99.9/457.4 MB 11.1 MB/s eta 0:00:33
     -------- ---------------------------- 102.5/457.4 MB 11.1 MB/s eta 0:00:32
     -------- ---------------------------- 105.1/457.4 MB 11.2 MB/s eta 0:00:32
     -------- ---------------------------- 107.7/457.4 MB 11.2 MB/s eta 0:00:32
     -------- ---------------------------- 110.4/457.4 MB 11.2 MB/s eta 0:00:31
     --------- --------------------------- 113.0/457.4 MB 11.2 MB/s eta 0:00:31
     --------- --------------------------- 115.6/457.4 MB 11.2 MB/s eta 0:00:31
     --------- --------------------------- 118.2/457.4 MB 11.2 MB/s eta 0:00:31
     --------- --------------------------- 120.6/457.4 MB 11.3 MB/s eta 0:00:30
     --------- --------------------------- 123.2/457.4 MB 11.3 MB/s eta 0:00:30
     ---------- -------------------------- 125.8/457.4 MB 11.3 MB/s eta 0:00:30
     ---------- -------------------------- 128.2/457.4 MB 11.3 MB/s eta 0:00:30
     ---------- -------------------------- 130.5/457.4 MB 11.3 MB/s eta 0:00:29
     ---------- -------------------------- 133.2/457.4 MB 11.3 MB/s eta 0:00:29
     ---------- -------------------------- 135.8/457.4 MB 11.3 MB/s eta 0:00:29
     ----------- ------------------------- 138.4/457.4 MB 11.3 MB/s eta 0:00:29
     ----------- ------------------------- 141.0/457.4 MB 11.3 MB/s eta 0:00:28
     ----------- ------------------------- 143.4/457.4 MB 11.3 MB/s eta 0:00:28
     ----------- ------------------------- 146.0/457.4 MB 11.3 MB/s eta 0:00:28
     ------------ ------------------------ 148.6/457.4 MB 11.3 MB/s eta 0:00:28
     ------------ ------------------------ 151.3/457.4 MB 11.3 MB/s eta 0:00:27
     ------------ ------------------------ 153.9/457.4 MB 11.4 MB/s eta 0:00:27
     ------------ ------------------------ 156.5/457.4 MB 11.4 MB/s eta 0:00:27
     ------------ ------------------------ 159.1/457.4 MB 11.4 MB/s eta 0:00:27
     ------------- ----------------------- 161.7/457.4 MB 11.4 MB/s eta 0:00:26
     ------------- ----------------------- 164.4/457.4 MB 11.4 MB/s eta 0:00:26
     ------------- ----------------------- 166.7/457.4 MB 11.4 MB/s eta 0:00:26
     ------------- ----------------------- 169.3/457.4 MB 11.4 MB/s eta 0:00:26
     ------------- ----------------------- 172.0/457.4 MB 11.4 MB/s eta 0:00:26
     -------------- ---------------------- 174.6/457.4 MB 11.4 MB/s eta 0:00:25
     -------------- ---------------------- 177.2/457.4 MB 11.4 MB/s eta 0:00:25
     -------------- ---------------------- 179.8/457.4 MB 11.4 MB/s eta 0:00:25
     -------------- ---------------------- 182.5/457.4 MB 11.4 MB/s eta 0:00:25
     -------------- ---------------------- 184.8/457.4 MB 11.4 MB/s eta 0:00:24
     --------------- --------------------- 187.7/457.4 MB 11.4 MB/s eta 0:00:24
     --------------- --------------------- 190.3/457.4 MB 11.4 MB/s eta 0:00:24
     --------------- --------------------- 192.9/457.4 MB 11.4 MB/s eta 0:00:24
     --------------- --------------------- 194.5/457.4 MB 11.4 MB/s eta 0:00:24
     --------------- --------------------- 197.1/457.4 MB 11.4 MB/s eta 0:00:23
     ---------------- -------------------- 199.8/457.4 MB 11.4 MB/s eta 0:00:23
     ---------------- -------------------- 202.1/457.4 MB 11.4 MB/s eta 0:00:23
     ---------------- -------------------- 204.7/457.4 MB 11.4 MB/s eta 0:00:23
     ---------------- -------------------- 207.4/457.4 MB 11.4 MB/s eta 0:00:22
     ---------------- -------------------- 210.0/457.4 MB 11.4 MB/s eta 0:00:22
     ----------------- ------------------- 212.6/457.4 MB 11.4 MB/s eta 0:00:22
     ----------------- ------------------- 215.0/457.4 MB 11.4 MB/s eta 0:00:22
     ----------------- ------------------- 217.6/457.4 MB 11.4 MB/s eta 0:00:21
     ----------------- ------------------- 220.2/457.4 MB 11.4 MB/s eta 0:00:21
     ------------------ ------------------ 223.1/457.4 MB 11.4 MB/s eta 0:00:21
     ------------------ ------------------ 225.4/457.4 MB 11.4 MB/s eta 0:00:21
     ------------------ ------------------ 227.8/457.4 MB 11.4 MB/s eta 0:00:21
     ------------------ ------------------ 230.2/457.4 MB 11.4 MB/s eta 0:00:20
     ------------------ ------------------ 232.8/457.4 MB 11.4 MB/s eta 0:00:20
     ------------------- ----------------- 235.7/457.4 MB 11.4 MB/s eta 0:00:20
     ------------------- ----------------- 237.8/457.4 MB 11.4 MB/s eta 0:00:20
     ------------------- ----------------- 240.1/457.4 MB 11.4 MB/s eta 0:00:20
     ------------------- ----------------- 242.7/457.4 MB 11.4 MB/s eta 0:00:19
     ------------------- ----------------- 245.4/457.4 MB 11.4 MB/s eta 0:00:19
     -------------------- ---------------- 248.0/457.4 MB 11.4 MB/s eta 0:00:19
     -------------------- ---------------- 250.6/457.4 MB 11.4 MB/s eta 0:00:19
     -------------------- ---------------- 253.2/457.4 MB 11.4 MB/s eta 0:00:18
     -------------------- ---------------- 255.6/457.4 MB 11.4 MB/s eta 0:00:18
     -------------------- ---------------- 258.2/457.4 MB 11.4 MB/s eta 0:00:18
     --------------------- --------------- 260.8/457.4 MB 11.5 MB/s eta 0:00:18
     --------------------- --------------- 263.2/457.4 MB 11.5 MB/s eta 0:00:17
     --------------------- --------------- 265.8/457.4 MB 11.5 MB/s eta 0:00:17
     --------------------- --------------- 268.4/457.4 MB 11.5 MB/s eta 0:00:17
     --------------------- --------------- 271.1/457.4 MB 11.5 MB/s eta 0:00:17
     ---------------------- -------------- 273.4/457.4 MB 11.5 MB/s eta 0:00:17
     ---------------------- -------------- 276.0/457.4 MB 11.5 MB/s eta 0:00:16
     ---------------------- -------------- 278.4/457.4 MB 11.5 MB/s eta 0:00:16
     ---------------------- -------------- 280.5/457.4 MB 11.5 MB/s eta 0:00:16
     ---------------------- -------------- 283.4/457.4 MB 11.5 MB/s eta 0:00:16
     ----------------------- ------------- 286.3/457.4 MB 11.5 MB/s eta 0:00:15
     ----------------------- ------------- 288.6/457.4 MB 11.5 MB/s eta 0:00:15
     ----------------------- ------------- 292.8/457.4 MB 11.5 MB/s eta 0:00:15
     ----------------------- ------------- 295.4/457.4 MB 11.5 MB/s eta 0:00:15
     ------------------------ ------------ 298.1/457.4 MB 11.5 MB/s eta 0:00:14
     ------------------------ ------------ 300.7/457.4 MB 11.5 MB/s eta 0:00:14
     ------------------------ ------------ 303.0/457.4 MB 11.5 MB/s eta 0:00:14
     ------------------------ ------------ 305.7/457.4 MB 11.5 MB/s eta 0:00:14
     ------------------------ ------------ 308.3/457.4 MB 11.6 MB/s eta 0:00:13
     ------------------------- ----------- 310.6/457.4 MB 11.6 MB/s eta 0:00:13
     ------------------------- ----------- 313.0/457.4 MB 11.6 MB/s eta 0:00:13
     ------------------------- ----------- 315.6/457.4 MB 11.6 MB/s eta 0:00:13
     ------------------------- ----------- 317.7/457.4 MB 11.6 MB/s eta 0:00:13
     ------------------------- ----------- 320.3/457.4 MB 11.6 MB/s eta 0:00:12
     -------------------------- ---------- 322.7/457.4 MB 11.6 MB/s eta 0:00:12
     -------------------------- ---------- 325.1/457.4 MB 11.6 MB/s eta 0:00:12
     -------------------------- ---------- 327.7/457.4 MB 11.6 MB/s eta 0:00:12
     -------------------------- ---------- 330.3/457.4 MB 11.6 MB/s eta 0:00:11
     -------------------------- ---------- 332.9/457.4 MB 11.6 MB/s eta 0:00:11
     --------------------------- --------- 335.5/457.4 MB 11.6 MB/s eta 0:00:11
     --------------------------- --------- 338.2/457.4 MB 11.6 MB/s eta 0:00:11
     --------------------------- --------- 340.8/457.4 MB 11.6 MB/s eta 0:00:11
     --------------------------- --------- 343.1/457.4 MB 11.6 MB/s eta 0:00:10
     --------------------------- --------- 345.8/457.4 MB 11.6 MB/s eta 0:00:10
     ---------------------------- -------- 348.4/457.4 MB 11.6 MB/s eta 0:00:10
     ---------------------------- -------- 350.7/457.4 MB 11.6 MB/s eta 0:00:10
     ---------------------------- -------- 354.2/457.4 MB 11.6 MB/s eta 0:00:09
     ---------------------------- -------- 357.6/457.4 MB 11.7 MB/s eta 0:00:09
     ----------------------------- ------- 360.2/457.4 MB 11.7 MB/s eta 0:00:09
     ----------------------------- ------- 362.8/457.4 MB 11.7 MB/s eta 0:00:09
     ----------------------------- ------- 365.4/457.4 MB 11.7 MB/s eta 0:00:08
     ----------------------------- ------- 368.1/457.4 MB 11.7 MB/s eta 0:00:08
     ----------------------------- ------- 370.4/457.4 MB 11.7 MB/s eta 0:00:08
     ------------------------------ ------ 373.0/457.4 MB 11.7 MB/s eta 0:00:08
     ------------------------------ ------ 375.7/457.4 MB 11.7 MB/s eta 0:00:08
     ------------------------------ ------ 378.3/457.4 MB 11.7 MB/s eta 0:00:07
     ------------------------------ ------ 380.6/457.4 MB 11.7 MB/s eta 0:00:07
     ------------------------------- ----- 383.3/457.4 MB 11.7 MB/s eta 0:00:07
     ------------------------------- ----- 385.6/457.4 MB 11.6 MB/s eta 0:00:07
     ------------------------------- ----- 388.2/457.4 MB 11.7 MB/s eta 0:00:06
     ------------------------------- ----- 390.9/457.4 MB 11.7 MB/s eta 0:00:06
     ------------------------------- ----- 393.5/457.4 MB 11.7 MB/s eta 0:00:06
     -------------------------------- ---- 395.8/457.4 MB 11.7 MB/s eta 0:00:06
     -------------------------------- ---- 398.5/457.4 MB 11.7 MB/s eta 0:00:06
     -------------------------------- ---- 401.1/457.4 MB 11.7 MB/s eta 0:00:05
     -------------------------------- ---- 403.4/457.4 MB 11.7 MB/s eta 0:00:05
     -------------------------------- ---- 406.1/457.4 MB 11.7 MB/s eta 0:00:05
     --------------------------------- --- 408.7/457.4 MB 11.7 MB/s eta 0:00:05
     --------------------------------- --- 411.3/457.4 MB 11.7 MB/s eta 0:00:04
     --------------------------------- --- 413.7/457.4 MB 11.7 MB/s eta 0:00:04
     --------------------------------- --- 416.3/457.4 MB 11.7 MB/s eta 0:00:04
     --------------------------------- --- 418.9/457.4 MB 11.7 MB/s eta 0:00:04
     ---------------------------------- -- 421.0/457.4 MB 11.7 MB/s eta 0:00:04
     ---------------------------------- -- 423.9/457.4 MB 11.7 MB/s eta 0:00:03
     ---------------------------------- -- 426.5/457.4 MB 11.7 MB/s eta 0:00:03
     ---------------------------------- -- 429.1/457.4 MB 11.7 MB/s eta 0:00:03
     ---------------------------------- -- 431.8/457.4 MB 11.7 MB/s eta 0:00:03
     ----------------------------------- - 434.4/457.4 MB 11.7 MB/s eta 0:00:02
     ----------------------------------- - 437.0/457.4 MB 11.7 MB/s eta 0:00:02
     ----------------------------------- - 439.4/457.4 MB 11.7 MB/s eta 0:00:02
     ----------------------------------- - 442.0/457.4 MB 11.7 MB/s eta 0:00:02
     ----------------------------------- - 444.6/457.4 MB 11.7 MB/s eta 0:00:02
     ------------------------------------  447.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  449.6/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  452.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  454.6/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------  457.2/457.4 MB 11.7 MB/s eta 0:00:01
     ------------------------------------- 457.4/457.4 MB 11.0 MB/s eta 0:00:00
Requirement already satisfied: spacy-curated-transformers<1.0.0,>=0.2.2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from en-core-web-trf==3.8.0) (0.3.1)
Requirement already satisfied: curated-transformers<0.2.0,>=0.1.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.1.1)
Requirement already satisfied: curated-tokenizers<0.1.0,>=0.0.9 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.0.9)
Requirement already satisfied: torch>=1.12.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.8.0)
Requirement already satisfied: regex>=2022 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2025.9.18)
Requirement already satisfied: filelock in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.14.0)
Requirement already satisfied: networkx in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.5)
Requirement already satisfied: jinja2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.1.6)
Requirement already satisfied: fsspec in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2025.9.0)
Requirement already satisfied: setuptools in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (78.1.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from sympy>=1.13.3->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from jinja2->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.1.5)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')

In [2]:
def load_model():
    nlp = spacy.load("en_core_web_trf")
    return nlp

In [37]:
!pip install spacy[transformers]

Requirement already satisfied: spacy[transformers] in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (3.8.7)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (0.19.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (2.2.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (2.11.9)
Requirement already satisfied: jinja2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (3.1.6)
Requirement already satisfied: setuptools in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (78.1.1)
Requirement already satisfied: packaging>=20.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (3.5.0)
Requirement already satisfied: spacy_transformers<1.4.0,>=1.1.2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy[transformers]) (1.3.9)
Requirement already satisfied: language-data>=1.2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy[transformers]) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[transformers]) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[transformers]) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[transformers]) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy[transformers]) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy[transformers]) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy[transformers]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy[transformers]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy[transformers]) (2025.8.3)
Requirement already satisfied: transformers<4.50.0,>=3.4.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (4.44.0)
Requirement already satisfied: torch>=1.8.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (2.8.0)
Requirement already satisfied: spacy-alignments<1.0.0,>=0.7.2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (0.9.2)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy[transformers]) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy[transformers]) (0.1.5)
Requirement already satisfied: colorama in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy[transformers]) (0.4.6)
Requirement already satisfied: filelock in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (0.24.5)
Requirement already satisfied: pyyaml>=5.1 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (2025.9.18)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (0.6.2)
Requirement already satisfied: tokenizers<0.20,>=0.19 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (0.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from huggingface-hub<1.0,>=0.23.2->transformers<4.50.0,>=3.4.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (2025.9.0)
Requirement already satisfied: click>=8.0.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy[transformers]) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy[transformers]) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy[transformers]) (14.1.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy[transformers]) (0.22.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy[transformers]) (7.3.1)
Requirement already satisfied: wrapt in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy[transformers]) (1.17.3)
Requirement already satisfied: marisa-trie>=1.1.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy[transformers]) (1.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[transformers]) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[transformers]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy[transformers]) (0.1.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (1.14.0)
Requirement already satisfied: networkx in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (3.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from sympy>=1.13.3->torch>=1.8.0->spacy_transformers<1.4.0,>=1.1.2->spacy[transformers]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\shawa\downloads\football-analysis\venv\lib\site-packages (from jinja2->spacy[transformers]) (2.1.5)

In [4]:
nlp_model = load_model()
nlp_model

In [59]:
import os 
import sys
import pathlib
folder_path = pathlib.Path().parent.resolve()
sys.path.append(os.path.join(folder_path, '../'))
from utils import load_dataset
dataset_path = "../data/Subtitles/"
df = load_dataset(dataset_path)
df

     epsiode_num                                             script
0              1  A long time ago, a powerful demon fox appeared...
1              2  C'mon!\n Running like a fugitive,\n Being chas...
2              3  C'mon!\n Running like a fugitive,\n Being chas...
3              4  C'mon!\n Running like a fugitive,\n Being chas...
4              5  C'mon!\n Running like a fugitive,\n Being chas...
..           ...                                                ...
213          216  Summoning Jutsu!\n Oh, long time no see.\n We ...
214          217  Gaara.\n Kankuro.\n Gaara.\n Primary Lotus!\n ...
215          218  To think the Leaf’s reinforcements will be you...
216          219  Fly into the wavy and twisted sky, into your h...
217          220  So this is the Shukaku?\n It’s the first time ...

[218 rows x 2 columns]

     epsiode_num                                             script
0              1  A long time ago, a powerful demon fox appeared...
1              2  C'mon!\n Running like a fugitive,\n Being chas...
2              3  C'mon!\n Running like a fugitive,\n Being chas...
3              4  C'mon!\n Running like a fugitive,\n Being chas...
4              5  C'mon!\n Running like a fugitive,\n Being chas...
..           ...                                                ...
213          216  Summoning Jutsu!\n Oh, long time no see.\n We ...
214          217  Gaara.\n Kankuro.\n Gaara.\n Primary Lotus!\n ...
215          218  To think the Leaf’s reinforcements will be you...
216          219  Fly into the wavy and twisted sky, into your h...
217          220  So this is the Shukaku?\n It’s the first time ...

[218 rows x 2 columns]

In [60]:
def get_inference(script):
    script_sentences = sent_tokenize(script)

    output = []

    for sentence in script_sentences:
        doc = nlp_model(sentence)
        ners = set()
        for entity in doc.ents:
            if entity.label_ =="PERSON":
                full_name = entity.text
                first_name = entity.text.split(" ")[0]
                first_name = first_name.strip()
                ners.add(first_name)
        output.append(ners)

    return output

In [61]:
df = df.head(10)
df

   epsiode_num                                             script
0            1  A long time ago, a powerful demon fox appeared...
1            2  C'mon!\n Running like a fugitive,\n Being chas...
2            3  C'mon!\n Running like a fugitive,\n Being chas...
3            4  C'mon!\n Running like a fugitive,\n Being chas...
4            5  C'mon!\n Running like a fugitive,\n Being chas...
5            6  C'mon!\n Running like a fugitive,\n Being chas...
6            7  C'mon!\n Running like a fugitive,\n Being chas...
7            8  C'mon!\n Running like a fugitive,\n Being chas...
8            9  C'mon!\n Running like a fugitive,\n Being chas...
9           12  C'mon!\n Running like a fugitive,\n Being chas...

In [62]:
df["characters"] = df['script'].apply(get_inference)

C:\Users\shawa\AppData\Local\Temp\ipykernel_7680\2233959972.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["characters"] = df['script'].apply(get_inference)

In [63]:
df

,epsiode_num,script,characters
0,1,"A long time ago, a powerful demon fox appeared...","[{}, {}, {}, {}, {}, {}, {}, {Naruto}, {}, {},..."
1,2,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {Konohama..."
2,3,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {Sakura, Sasuke}, {}, {Konohamaru..."
3,4,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {Naruto}, {}, {}, {Iruka}, {}, {N..."
4,5,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
5,6,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {Sasuke}, {}, {Naruto}, {}, {Naruto},..."
6,7,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
7,8,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {Sasuke}, {}, {},..."
8,9,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
9,12,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {Zabuza}, {}, {}, {}, {Naruto..."

In [64]:
def generate_character_network(df):
    window_size = 10
    entity_relationship  =  []
    for row in df['characters']:
        entities_in_window = []
        for sentence in row:
            entities_in_window.append(list(sentence))
            entities_in_window= entities_in_window[-window_size:]
            entities_flattened = sum(entities_in_window, [])
            for entity in sentence:
                for entity_in_window in entities_flattened:
                    if entity != entity_in_window:
                        entity_relationship.append(sorted([entity, entity_in_window]))
    relationship_df = pd.DataFrame({"value":entity_relationship})
    relationship_df["source"] = relationship_df['value'].apply(lambda x : x[0])
    relationship_df["target"] = relationship_df['value'].apply(lambda x : x[1])
    relationship_df = relationship_df.groupby(['source', 'target']).count().reset_index()
    relationship_df = relationship_df.sort_values('value', ascending=False)
    return relationship_df

In [65]:
relationship_df = generate_character_network(df)
relationship_df.head (100)

        source   target  value
164     Naruto   Sasuke    122
203     Sakura   Sasuke     69
90       Iruka   Naruto     45
163     Naruto   Sakura     40
155     Mizuki   Naruto     29
..         ...      ...    ...
165     Naruto   Sensei      3
80       Inari  Kakashi      3
131       Kiba   Naruto      3
28       Fatty   Naruto      2
227  Sharingan      Uma      2

[100 rows x 3 columns]

In [66]:
import networkx as nx
from pyvis.network import Network

G = nx.from_pandas_edgelist(
    relationship_df, 
    source='source', 
    target='target', 
    edge_attr='value',
    create_using=nx.Graph()
)

net = Network(notebook=True, width="1000px", height="700px", bgcolor="#222222", font_color="white", cdn_resources="remote")
node_degree = dict(G.degree)

nx.set_node_attributes(G, node_degree, 'size')
net.from_nx(G)
net.show("naruto.html")

naruto.html

In [29]:
df

,epsiode_num,script,characters
0,1,"A long time ago, a powerful demon fox appeared...","[{}, {}, {}, {}, {}, {}, {}, {Naruto}, {}, {},..."
1,2,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {Konohama..."
2,3,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {Sakura, Sasuke}, {}, {Konohamaru..."
3,4,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {Naruto}, {}, {}, {Iruka}, {}, {N..."
4,5,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
5,6,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {Sasuke}, {}, {Naruto}, {}, {Naruto},..."
6,7,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
7,8,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {Sasuke}, {}, {},..."
8,9,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {..."
9,12,"C'mon!\n Running like a fugitive,\n Being chas...","[{}, {}, {}, {}, {Zabuza}, {}, {}, {}, {Naruto..."