In [88]:
from transformers import pipeline
from nltk import sent_tokenize 
import nltk
import torch
from glob import glob 
import pandas as pd
import numpy as np

In [3]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shawa\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [4]:
model_name = "facebook/bart-large-mnli"
device = 0 if torch.cuda.is_available() else 'cpu'

In [5]:
device

'cpu'

In [6]:
def load_model(device):
    theme_classifier = pipeline(
        "zero-shot-classification",
        model=model_name,
        device=device
    )

    return theme_classifier

In [7]:
import os
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

theme_classifier = load_model(device)

WARNING:tensorflow:From c:\Users\shawa\Downloads\football-analysis\venv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

c:\Users\shawa\Downloads\football-analysis\venv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [8]:
theme_list = ["friendship","hope","sacrifice","battle","self development","betrayal","love","dialogue"]

In [9]:
theme_classifier(
    "I gave him a right hook then a left jab",
    theme_list,
    multi_label=True
)

{'sequence': 'I gave him a right hook then a left jab',
 'labels': ['battle',
  'self development',
  'hope',
  'sacrifice',
  'dialogue',
  'betrayal',
  'love',
  'friendship'],
 'scores': [0.9121252298355103,
  0.4750025272369385,
  0.08781788498163223,
  0.04500041902065277,
  0.02013299986720085,
  0.012040478177368641,
  0.004292412661015987,
  0.002817223547026515]}

In [21]:
files = glob('../data/Subtitles/*.ass')
len(files)

218

In [29]:
with open(files[0],'r') as file:
    lines = file.readlines()
    lines = lines[27:]
    lines = [ ",".join(line.split(",")[9:]) for line in lines]
    print(lines)

['A long time ago, a powerful demon fox\\Nappeared with nine tails.\n', 'With its powerful tails,\n', 'it could smash mountains\\Nand create tidal waves.\n', 'A band of Ninjas rose to\\Ndefend their village from attack.\n', 'We have to wait until\\Nthe Fourth Hokage gets here!\n', "We can't let it get any closer\\Nto our village!\n", 'One great Ninja was able to\\Nimprison the monster,\n', 'but died in the process.\n', 'This Ninja was known as…\\Nthe Fourth Hokage.\n', 'Naruto!\n', 'Why did you do such a thing?!\n', "You're really gonna get it this time!\n", "I don't care!\n", 'You know your problem?\n', "You can't do the things I do!\n", 'Only I can do this!\n', "I'm better than all of you!\\NBelieve it!\n", "There's a problem, sir!\n", 'Lord Hokage!\n', 'What is it?\n', 'Did that Naruto do something again?\n', 'Yes. He climbed onto\\Nthe Mountainside Images…\n', 'And he vandalized and\\Ngraffitied all over them!\n', 'Wait!\n', 'Ha ha…\n', 'Why should I?\n', 'Hey, Naruto!\n', 'How did you suddenly get here,\\Nlruka Sensei?\n', 'The question is what are you doing here\\Nwhen you should be in class now?\n', 'Now listen, Naruto.\n', 'You failed the last graduation test\\Nand the one before that.\n', 'This is no time\\Nto be goofing off, you fool!\n', 'We will have a re-test on\\Nthe Transformation Jutsu!\n', 'Even those who already passed\\Nwill take it!\n', 'Whaaaat?!\n', 'Sakura Haruno. Here I go…\n', 'Transform!\n', 'OK!\n', 'I did it!\n', 'Cha!\n', 'Did you see that, Sasuke?\n', 'Next, Sasuke Uchiha.\n', 'Yes.\n', 'O-OK.\n', 'Next, Naruto Uzumaki.\n', 'This is a real pain.\n', "And it's all your fault.\n", 'Like I care!!\n', 'OK…\n', 'Good luck, Naruto…\n', 'Transform!\n', 'How was it?\n', 'I call it the "Sexy Jutsu"!\n', 'You fool!\\NStop making idiotic spells!\n', 'Darn…\n', 'Darn…\n', "I won't let you go home\\Nunless you clean that all up.\n", "I don't care…\n", "There's nobody home anyway.\n", 'Naruto...\n', 'What is it this time?\n', 'What I meant was…\n', "If you clean up all that mess,\\NI'll buy you ramen tonight.\n", 'Huh?!\n', 'Yes!\\NI-I will finish it no time!\n', 'Enter: Naruto Uzumaki!\n', 'Naruto.\n', 'Why did you vandalize those faces?\n', "Don't you know who\\Nthe Hokage leaders are?\n", 'Of course, I do!\n', 'I know they earned the title\\NLord Hokage\n', 'because they were the best Ninja\\Nof their time, right?\n', 'Especially the Fourth Hokage\\Nwas a hero\n', 'who saved the village from\\Nthe nine-tail demon fox.\n', 'Then why did you do that?\n', "Because I'll become a Hokage myself.\n", "And I'll be the greatest Hokage\\Nof all time!\n", 'So that everyone will finally\\Nlearn to accept me!\n', 'By the way, Sensei,\\NI have a favor to ask.\n', 'You want another bowl?\n', 'Mmmm…No…\n', 'Can I borrow that Leaf headband\\Nfor a while?\n', 'This?\n', 'No no!\n', 'This is worn only by those who\\Nhave graduated from Ninja Academy.\n', 'Tomorrow, you will…\n', "You're so mean!\n", "So that's why you took off\\Nyour goggles…\n", 'Humph...\\NOne more bowl please!\n', 'We are now about to begin\\Nthe graduation test.\n', 'When your name is called,\\Nproceed to the next classroom.\n', 'The test is on the Clone Jutsu.\n', 'Oh no…\n', 'Of all the…! That is my weakest Jutsu!\n', 'But still…\\NI will do it no matter what!\n', 'Clone Jutsu!\n', 'Disqualified!\n', 'Iruka Sensei.\n', 'His physical coordination\\Nand stamina are excellent.\n', 'And he managed to come up\\Nwith something.\n', "Isn't that enough\\Nfor him to pass?\n", 'Mizuki Sensei...\\NAll the others created three or more clones.\n', 'Naruto created just one.\n', "And it's practically useless.\\NI can't give him a passing mark.\n", "I 'm a Ninja now!\n", "You did well. That's my son.\n", 'Congratulations for your graduation.\n', "I'll cook something good tonight!\n", 'Look at that one.\n', "It's that boy.\\NI hear he's the only one who failed.\n", 'Serves him right.\n', 'Imagine what would happen\\Nif he became a Ninja.\n', "Isn't that the boy\\Nwho is actually…\n", "Hey! We're not supposed to\\Ntalk about that.\n", 'Iruka.\\NWe need to talk later.\n', 'Yes, sir.\n', "Iruka Sensei isn't trying\\Nto be mean to you.\n", 'Then why only me?\n', 'He wants you to become strong\\Nfrom the bottom of his heart.\n', "You both don't have parents.\n", 'But I really wanted to graduate.\n', 'Heh... I guess I have no choice…\n', "I'll let you in on a big secret.\n", 'Secret?\n', 'Iruka.\n', 'What is it, Lord Hokage?\n', 'I know how you feel. But…\n', 'Naruto also grew up without knowing\\Nthe love of his parents…like you.\n', 'Let me go!\n', 'My mom and dad are\\Nstill out there fighting!\n', 'Wake up, Iruka Sensei!\n', "What's the matter?\n", "Come to Lord Hokage's immediately!\n", 'I heard that Naruto…\\Nstole the Scroll of Sealing.\n', 'The Scroll of Sealing?!\n', "Let's see…\n", 'The first Jutsu is…\\NMulti-Shadow Clone Jutsu?\n', "What?! Already a Jutsu I'm no good at?\n", "Lord Hokage!\\NWe can't forgive him!\n", 'This is not just a prank!\n', 'The Scroll is a dangerous item\\Nthat the First Hokage sealed!\n', 'Depending on its use…\n', 'It will be a major disaster if\\Nit is taken out of the village!\n', 'Yes. Bring Naruto here at once!\n', 'Yes, sir!\n', 'Where did you go…Naruto?\n', 'I will tell everyone in the village\\Nabout this and eliminate Naruto…\n', 'Then the Scroll of Sealing\\Nwill be mine!\n', 'Hey you, Naruto!\n', 'You found me..\n', "And I've only learned one Jutsu.\n", "He's been practicing the Jutsu…\n", "until he's become\\Nthis exhausted and dirty…?\n", "Listen, listen!\\NI'm gonna show you this amazing Jutsu!\n", "You're gonna let me graduate\\Nif I can do it!\n", "Isn't it true that I can graduate if\\NI can do one of the Jutsu written here?\n", 'Who told you that?\n', 'Mizuki Sensei. He told me\\Nabout this scroll, and this place…\n', 'Mizuki did?!\n', "I'm impressed you found this place.\n", 'I see now…how it is.\n', 'Naruto, give me that scroll.\n', "Wait, wait…\\NWhat's going on here?\n", 'Naruto! Never give him that scroll!\n', 'It is a dangerous object that contains\\Nforbidden Ninja Jutsu. It was sealed.\n', 'Mizuki used you in order to\\Nget it for himself!\n', 'W-Wha--?\n', 'Naruto, Iruka is only afraid of\\Nyou holding that scroll!\n', 'Huh?\n', "What are you saying, Mizuki!\\NDon't let him fool you, Naruto!\n", 'I will tell you the truth.\n', "Idiot! Don't do that!\n", 'After an incident 12 years ago,\\Na rule was created.\n', 'A rule?\n', 'That is, Naruto, a rule everybody\\Nbut you knows.\n', 'Except me?! \t\t\t\t\tWhat is it?\n', 'Stop it, Mizuki!\n', 'The rule forbids anyone from revealing\\Nthat you are actually the Demon Fox Spirit!\n', 'Huh?\n', 'You are actually the Demon,\\NNine-Tailed Fox Spirit,\n', "who killed Iruka's parents and\\Ndestroyed our village!\n", 'Stop it!\n', 'Everyone has been\\Ndeceiving you ever since.\n', "Didn't you find it strange?\n", 'Why everyone hated you so much?\n', 'No! No! No! No! No!\n', 'Naruto…\n', "Nobody accepts you.\\NThat's why Iruka hates you so much!\n", 'Iruka... Naruto grew up\\Nwithout the love of parents.\n', 'Everyone avoids him like\\Nthe plague after what happened.\n', "That's why he keeps misbehaving.\n", "It's the only way for him to get\\Nany attention or acknowledgement.\n", 'He pretends to be tough,\\Nbut inside he is really hurting.\n', 'Die, Naruto!\n', 'Naruto! \t\t\t\t\tGet down!\n', 'Why…?\n', 'Because you and I are the same.\n', 'After my parents died,\n', 'nobody paid attention to me\\Nor gave me any support.\n', "I wasn't a good student in school.\n", 'I was the class clown…\\Nbecause I wanted people to notice me.\n', "I couldn't get noticed through excellence,\\Nso I kept doing stupid things.\n", 'It was so hard.\n', "Isn't that right, Naruto?\n", 'You felt so lonely…right?\\NAnd you suffered inside, right?\n', "I'm sorry, Naruto….\n", "If I had been more responsible,\\Nmaybe you wouldn't have suffered so much.\n", "Don't make me laugh!\n", 'Iruka has always hated you,\\Never since you killed his parents!\n', "He's just saying all that\\Nto get the Scroll of Sealing back!\n", 'Naruto!\n', 'Narutoooooo!\n', 'He is not the type of kid\\Nwho will change his mind.\n', 'He will take revenge against\\Nour village using that scroll!\n', "Didn't you see his eyes?\\NThose are the eyes of a Demon Fox.\n", "No…\\NNaruto…isn't…like that at all!\n", 'All I want is to kill Naruto\\Nand get the scroll.\n', "I'll take care of you later!\n", "I-I won't let you…\n", 'Well, well.\n', 'Mizuki has a big mouth!\n', "Naruto feels worse than he's ever felt.\n", 'He might unleash\\Nthe power locked up inside him.\n', 'The Scroll of Sealing is now with him.\n', "There's a slight chance\\Nhe might actually release\n", 'the Nine-Tailed Fox Spirit\\Nsealed inside him!\n', 'If that happens…\n', "I've found him!\n", 'Naruto!\n', 'Everything that Mizuki said\\Nwas a lie!\n', 'Give me that scroll, quick!\\NMizuki is after the scroll!\n', "It can't be…\n", 'Why is it, Naruto?\n', 'How…\n', "did you know I wasn't Iruka…?\n", "Because I'm Iruka.\n", 'I see.\n', "What's in it for you to protect\\Nthe one who killed your family?\n", "I'm not gonna let a stupid idiot\\Nlike you get that scroll!\n", "You're the idiot.\\NNaruto is the same as me.\n", 'Same?\n', 'Anyone can do whatever\\Nhe wants once he has the scroll.\n', 'There is no way that that monster…\n', "that Fox Spirit, won't take advantage\\Nof the power of that scroll!\n", "You're right…\n", 'I guess it was true all along!\n', 'See, Iruka Sensei never really\\Ncared for me at all!\n', '...if he was the Demon Fox Spirit.\n', 'But Naruto is different!\n', 'I know that he is an exceptional student.\n', 'He works very hard,\n', "and he's single-minded\\Nand clumsy at the same time.\n", 'No one accepts him, but he knows\\Nthe meaning of human suffering.\n', 'He is not the Demon Fox Spirit.\n', "He's Naruto Uzumaki of\\Nthe Village Hidden in the Leaves!\n", 'You are so gullible. \t\t\t\t\tlruka!\n', 'I was gonna take you down later,\\Nbut I have changed my mind.\n', 'Die!\n', 'I guess this is the end for me…\n', 'Naruto?!\n', 'You surprised me there, freak.\n', "If you ever lay a hand on Iruka Sensei,\\NI'll kill you!\n", 'Shut up! I can take care of a kid\\Nlike you with a single blow!\n', "Why don't you try then?\\NI'll strike you back a thousand-fold!\n", "Let's see you try!\\NShow me what you can do, Demon Fox!\n", 'Shadow Clone Jutsu!\n', "Naruto! You've…\n", "Those aren't just images but actual clones!\\NThat's an advanced Ninjutsu!\n", "What's this…?\n", "What's the matter? \t\t\t\t\tC'mon!\n", "Weren't you gonna get me\\Nwith one blow? Here!\n", "In that case…\\NI'll come to you.\n", 'I kinda got carried away.\\Nlruka Sensei, are you okay?\n', 'Yeah.\n', "He's really something.\n", 'Maybe it is true.\n', 'Maybe he will surpass all\\Nthe Hokage leaders…\n', "Naruto, come over here.\\NI'd like to give you something.\n", 'Has anyone found Naruto yet?\n', 'No.\n', 'Darn, this is going to be bad…\n', "There's no need to worry anymore.\n", 'Lord Hokage!\n', "He'll be back soon.\n", 'Sensei, how much longer?\n', 'OK, you may open your eyes now.\n', 'Congratulations…on your graduation.\n', "In celebration, we'll have ramen tonight!\n", 'Iruka Sensei!\n', 'That hurts!\n', 'Naruto…\n', 'I was going to lecture to you...\n', "that the road gets more difficult\\Nnow that you're a Ninja.\n", "But I guess I'll just wait to tell you\\Nthat until we get to the ramen stand…\n", 'W-What do you want, you little shrimp?\\NQuit following me!\n', "You're smaller than me and\n", "you're saying that you're gonna\\Nbecome the Fifth Hokage?\n", "I don't care if you are the 3rd Hokage's\\Ngrandson or not.\n", "It's not that easy to be a Hokage!\n", "If you want it that bad,\\Nyou're gonna have to beat me first!\n", 'Next episode:\\N "My Name Is Konohamaru!"\n', 'Watch my outstanding performance!\n']

In [32]:
lines = [line.replace('\\N', ' ') for line in lines]
lines

['A long time ago, a powerful demon fox appeared with nine tails.\n',
 'With its powerful tails,\n',
 'it could smash mountains and create tidal waves.\n',
 'A band of Ninjas rose to defend their village from attack.\n',
 'We have to wait until the Fourth Hokage gets here!\n',
 "We can't let it get any closer to our village!\n",
 'One great Ninja was able to imprison the monster,\n',
 'but died in the process.\n',
 'This Ninja was known as… the Fourth Hokage.\n',
 'Naruto!\n',
 'Why did you do such a thing?!\n',
 "You're really gonna get it this time!\n",
 "I don't care!\n",
 'You know your problem?\n',
 "You can't do the things I do!\n",
 'Only I can do this!\n',
 "I'm better than all of you! Believe it!\n",
 "There's a problem, sir!\n",
 'Lord Hokage!\n',
 'What is it?\n',
 'Did that Naruto do something again?\n',
 'Yes. He climbed onto the Mountainside Images…\n',
 'And he vandalized and graffitied all over them!\n',
 'Wait!\n',
 'Ha ha…\n',
 'Why should I?\n',
 'Hey, Naruto!\n',
 'How did you suddenly get here, lruka Sensei?\n',
 'The question is what are you doing here when you should be in class now?\n',
 'Now listen, Naruto.\n',
 'You failed the last graduation test and the one before that.\n',
 'This is no time to be goofing off, you fool!\n',
 'We will have a re-test on the Transformation Jutsu!\n',
 'Even those who already passed will take it!\n',
 'Whaaaat?!\n',
 'Sakura Haruno. Here I go…\n',
 'Transform!\n',
 'OK!\n',
 'I did it!\n',
 'Cha!\n',
 'Did you see that, Sasuke?\n',
 'Next, Sasuke Uchiha.\n',
 'Yes.\n',
 'O-OK.\n',
 'Next, Naruto Uzumaki.\n',
 'This is a real pain.\n',
 "And it's all your fault.\n",
 'Like I care!!\n',
 'OK…\n',
 'Good luck, Naruto…\n',
 'Transform!\n',
 'How was it?\n',
 'I call it the "Sexy Jutsu"!\n',
 'You fool! Stop making idiotic spells!\n',
 'Darn…\n',
 'Darn…\n',
 "I won't let you go home unless you clean that all up.\n",
 "I don't care…\n",
 "There's nobody home anyway.\n",
 'Naruto...\n',
 'What is it this time?\n',
 'What I meant was…\n',
 "If you clean up all that mess, I'll buy you ramen tonight.\n",
 'Huh?!\n',
 'Yes! I-I will finish it no time!\n',
 'Enter: Naruto Uzumaki!\n',
 'Naruto.\n',
 'Why did you vandalize those faces?\n',
 "Don't you know who the Hokage leaders are?\n",
 'Of course, I do!\n',
 'I know they earned the title Lord Hokage\n',
 'because they were the best Ninja of their time, right?\n',
 'Especially the Fourth Hokage was a hero\n',
 'who saved the village from the nine-tail demon fox.\n',
 'Then why did you do that?\n',
 "Because I'll become a Hokage myself.\n",
 "And I'll be the greatest Hokage of all time!\n",
 'So that everyone will finally learn to accept me!\n',
 'By the way, Sensei, I have a favor to ask.\n',
 'You want another bowl?\n',
 'Mmmm…No…\n',
 'Can I borrow that Leaf headband for a while?\n',
 'This?\n',
 'No no!\n',
 'This is worn only by those who have graduated from Ninja Academy.\n',
 'Tomorrow, you will…\n',
 "You're so mean!\n",
 "So that's why you took off your goggles…\n",
 'Humph... One more bowl please!\n',
 'We are now about to begin the graduation test.\n',
 'When your name is called, proceed to the next classroom.\n',
 'The test is on the Clone Jutsu.\n',
 'Oh no…\n',
 'Of all the…! That is my weakest Jutsu!\n',
 'But still… I will do it no matter what!\n',
 'Clone Jutsu!\n',
 'Disqualified!\n',
 'Iruka Sensei.\n',
 'His physical coordination and stamina are excellent.\n',
 'And he managed to come up with something.\n',
 "Isn't that enough for him to pass?\n",
 'Mizuki Sensei... All the others created three or more clones.\n',
 'Naruto created just one.\n',
 "And it's practically useless. I can't give him a passing mark.\n",
 "I 'm a Ninja now!\n",
 "You did well. That's my son.\n",
 'Congratulations for your graduation.\n',
 "I'll cook something good tonight!\n",
 'Look at that one.\n',
 "It's that boy. I hear he's the only one who failed.\n",
 'Serves him right.\n',
 'Imagine what would happen if he became a Ninja.\n',
 "Isn't that the boy who is actually…\n",
 "Hey! We're not supposed to talk about that.\n",
 'Iruka. We need to talk later.\n',
 'Yes, sir.\n',
 "Iruka Sensei isn't trying to be mean to you.\n",
 'Then why only me?\n',
 'He wants you to become strong from the bottom of his heart.\n',
 "You both don't have parents.\n",
 'But I really wanted to graduate.\n',
 'Heh... I guess I have no choice…\n',
 "I'll let you in on a big secret.\n",
 'Secret?\n',
 'Iruka.\n',
 'What is it, Lord Hokage?\n',
 'I know how you feel. But…\n',
 'Naruto also grew up without knowing the love of his parents…like you.\n',
 'Let me go!\n',
 'My mom and dad are still out there fighting!\n',
 'Wake up, Iruka Sensei!\n',
 "What's the matter?\n",
 "Come to Lord Hokage's immediately!\n",
 'I heard that Naruto… stole the Scroll of Sealing.\n',
 'The Scroll of Sealing?!\n',
 "Let's see…\n",
 'The first Jutsu is… Multi-Shadow Clone Jutsu?\n',
 "What?! Already a Jutsu I'm no good at?\n",
 "Lord Hokage! We can't forgive him!\n",
 'This is not just a prank!\n',
 'The Scroll is a dangerous item that the First Hokage sealed!\n',
 'Depending on its use…\n',
 'It will be a major disaster if it is taken out of the village!\n',
 'Yes. Bring Naruto here at once!\n',
 'Yes, sir!\n',
 'Where did you go…Naruto?\n',
 'I will tell everyone in the village about this and eliminate Naruto…\n',
 'Then the Scroll of Sealing will be mine!\n',
 'Hey you, Naruto!\n',
 'You found me..\n',
 "And I've only learned one Jutsu.\n",
 "He's been practicing the Jutsu…\n",
 "until he's become this exhausted and dirty…?\n",
 "Listen, listen! I'm gonna show you this amazing Jutsu!\n",
 "You're gonna let me graduate if I can do it!\n",
 "Isn't it true that I can graduate if I can do one of the Jutsu written here?\n",
 'Who told you that?\n',
 'Mizuki Sensei. He told me about this scroll, and this place…\n',
 'Mizuki did?!\n',
 "I'm impressed you found this place.\n",
 'I see now…how it is.\n',
 'Naruto, give me that scroll.\n',
 "Wait, wait… What's going on here?\n",
 'Naruto! Never give him that scroll!\n',
 'It is a dangerous object that contains forbidden Ninja Jutsu. It was sealed.\n',
 'Mizuki used you in order to get it for himself!\n',
 'W-Wha--?\n',
 'Naruto, Iruka is only afraid of you holding that scroll!\n',
 'Huh?\n',
 "What are you saying, Mizuki! Don't let him fool you, Naruto!\n",
 'I will tell you the truth.\n',
 "Idiot! Don't do that!\n",
 'After an incident 12 years ago, a rule was created.\n',
 'A rule?\n',
 'That is, Naruto, a rule everybody but you knows.\n',
 'Except me?! \t\t\t\t\tWhat is it?\n',
 'Stop it, Mizuki!\n',
 'The rule forbids anyone from revealing that you are actually the Demon Fox Spirit!\n',
 'Huh?\n',
 'You are actually the Demon, Nine-Tailed Fox Spirit,\n',
 "who killed Iruka's parents and destroyed our village!\n",
 'Stop it!\n',
 'Everyone has been deceiving you ever since.\n',
 "Didn't you find it strange?\n",
 'Why everyone hated you so much?\n',
 'No! No! No! No! No!\n',
 'Naruto…\n',
 "Nobody accepts you. That's why Iruka hates you so much!\n",
 'Iruka... Naruto grew up without the love of parents.\n',
 'Everyone avoids him like the plague after what happened.\n',
 "That's why he keeps misbehaving.\n",
 "It's the only way for him to get any attention or acknowledgement.\n",
 'He pretends to be tough, but inside he is really hurting.\n',
 'Die, Naruto!\n',
 'Naruto! \t\t\t\t\tGet down!\n',
 'Why…?\n',
 'Because you and I are the same.\n',
 'After my parents died,\n',
 'nobody paid attention to me or gave me any support.\n',
 "I wasn't a good student in school.\n",
 'I was the class clown… because I wanted people to notice me.\n',
 "I couldn't get noticed through excellence, so I kept doing stupid things.\n",
 'It was so hard.\n',
 "Isn't that right, Naruto?\n",
 'You felt so lonely…right? And you suffered inside, right?\n',
 "I'm sorry, Naruto….\n",
 "If I had been more responsible, maybe you wouldn't have suffered so much.\n",
 "Don't make me laugh!\n",
 'Iruka has always hated you, ever since you killed his parents!\n',
 "He's just saying all that to get the Scroll of Sealing back!\n",
 'Naruto!\n',
 'Narutoooooo!\n',
 'He is not the type of kid who will change his mind.\n',
 'He will take revenge against our village using that scroll!\n',
 "Didn't you see his eyes? Those are the eyes of a Demon Fox.\n",
 "No… Naruto…isn't…like that at all!\n",
 'All I want is to kill Naruto and get the scroll.\n',
 "I'll take care of you later!\n",
 "I-I won't let you…\n",
 'Well, well.\n',
 'Mizuki has a big mouth!\n',
 "Naruto feels worse than he's ever felt.\n",
 'He might unleash the power locked up inside him.\n',
 'The Scroll of Sealing is now with him.\n',
 "There's a slight chance he might actually release\n",
 'the Nine-Tailed Fox Spirit sealed inside him!\n',
 'If that happens…\n',
 "I've found him!\n",
 'Naruto!\n',
 'Everything that Mizuki said was a lie!\n',
 'Give me that scroll, quick! Mizuki is after the scroll!\n',
 "It can't be…\n",
 'Why is it, Naruto?\n',
 'How…\n',
 "did you know I wasn't Iruka…?\n",
 "Because I'm Iruka.\n",
 'I see.\n',
 "What's in it for you to protect the one who killed your family?\n",
 "I'm not gonna let a stupid idiot like you get that scroll!\n",
 "You're the idiot. Naruto is the same as me.\n",
 'Same?\n',
 'Anyone can do whatever he wants once he has the scroll.\n',
 'There is no way that that monster…\n',
 "that Fox Spirit, won't take advantage of the power of that scroll!\n",
 "You're right…\n",
 'I guess it was true all along!\n',
 'See, Iruka Sensei never really cared for me at all!\n',
 '...if he was the Demon Fox Spirit.\n',
 'But Naruto is different!\n',
 'I know that he is an exceptional student.\n',
 'He works very hard,\n',
 "and he's single-minded and clumsy at the same time.\n",
 'No one accepts him, but he knows the meaning of human suffering.\n',
 'He is not the Demon Fox Spirit.\n',
 "He's Naruto Uzumaki of the Village Hidden in the Leaves!\n",
 'You are so gullible. \t\t\t\t\tlruka!\n',
 'I was gonna take you down later, but I have changed my mind.\n',
 'Die!\n',
 'I guess this is the end for me…\n',
 'Naruto?!\n',
 'You surprised me there, freak.\n',
 "If you ever lay a hand on Iruka Sensei, I'll kill you!\n",
 'Shut up! I can take care of a kid like you with a single blow!\n',
 "Why don't you try then? I'll strike you back a thousand-fold!\n",
 "Let's see you try! Show me what you can do, Demon Fox!\n",
 'Shadow Clone Jutsu!\n',
 "Naruto! You've…\n",
 "Those aren't just images but actual clones! That's an advanced Ninjutsu!\n",
 "What's this…?\n",
 "What's the matter? \t\t\t\t\tC'mon!\n",
 "Weren't you gonna get me with one blow? Here!\n",
 "In that case… I'll come to you.\n",
 'I kinda got carried away. lruka Sensei, are you okay?\n',
 'Yeah.\n',
 "He's really something.\n",
 'Maybe it is true.\n',
 'Maybe he will surpass all the Hokage leaders…\n',
 "Naruto, come over here. I'd like to give you something.\n",
 'Has anyone found Naruto yet?\n',
 'No.\n',
 'Darn, this is going to be bad…\n',
 "There's no need to worry anymore.\n",
 'Lord Hokage!\n',
 "He'll be back soon.\n",
 'Sensei, how much longer?\n',
 'OK, you may open your eyes now.\n',
 'Congratulations…on your graduation.\n',
 "In celebration, we'll have ramen tonight!\n",
 'Iruka Sensei!\n',
 'That hurts!\n',
 'Naruto…\n',
 'I was going to lecture to you...\n',
 "that the road gets more difficult now that you're a Ninja.\n",
 "But I guess I'll just wait to tell you that until we get to the ramen stand…\n",
 'W-What do you want, you little shrimp? Quit following me!\n',
 "You're smaller than me and\n",
 "you're saying that you're gonna become the Fifth Hokage?\n",
 "I don't care if you are the 3rd Hokage's grandson or not.\n",
 "It's not that easy to be a Hokage!\n",
 "If you want it that bad, you're gonna have to beat me first!\n",
 'Next episode:  "My Name Is Konohamaru!"\n',
 'Watch my outstanding performance!\n']

In [33]:
" ".join(lines[:10])

"A long time ago, a powerful demon fox appeared with nine tails.\n With its powerful tails,\n it could smash mountains and create tidal waves.\n A band of Ninjas rose to defend their village from attack.\n We have to wait until the Fourth Hokage gets here!\n We can't let it get any closer to our village!\n One great Ninja was able to imprison the monster,\n but died in the process.\n This Ninja was known as… the Fourth Hokage.\n Naruto!\n"

In [39]:
int(files[0].split(" ")[-1].split('.')[0].strip())

1

In [69]:
def load_dataset(data_path):
    files = glob(data_path+"/*.ass")
    scripts = []
    episodes = []
    for path in files:
        with open(path,'r') as file:
            lines = file.readlines()
            lines = lines[27:]
            lines = [ ",".join(line.split(",")[9:]) for line in lines]
        lines = [line.replace('\\N', ' ') for line in lines]
        script = " ".join(lines)
        episode = int(path.split('-')[-1].split('.')[0].strip())
        scripts.append(script)
        episodes.append(episode)
    df = pd.DataFrame({"epsiode_num":episodes, "script":scripts})
    return df

In [70]:
df = load_dataset("../data/Subtitles")

In [71]:
print(df)

     epsiode_num                                             script
0              1  A long time ago, a powerful demon fox appeared...
1              2  C'mon!\n Running like a fugitive,\n Being chas...
2              3  C'mon!\n Running like a fugitive,\n Being chas...
3              4  C'mon!\n Running like a fugitive,\n Being chas...
4              5  C'mon!\n Running like a fugitive,\n Being chas...
..           ...                                                ...
213          216  Summoning Jutsu!\n Oh, long time no see.\n We ...
214          217  Gaara.\n Kankuro.\n Gaara.\n Primary Lotus!\n ...
215          218  To think the Leaf’s reinforcements will be you...
216          219  Fly into the wavy and twisted sky, into your h...
217          220  So this is the Shukaku?\n It’s the first time ...

[218 rows x 2 columns]

In [77]:
script = df.iloc[0]['script']
print(script)

A long time ago, a powerful demon fox appeared with nine tails.
 With its powerful tails,
 it could smash mountains and create tidal waves.
 A band of Ninjas rose to defend their village from attack.
 We have to wait until the Fourth Hokage gets here!
 We can't let it get any closer to our village!
 One great Ninja was able to imprison the monster,
 but died in the process.
 This Ninja was known as… the Fourth Hokage.
 Naruto!
 Why did you do such a thing?!
 You're really gonna get it this time!
 I don't care!
 You know your problem?
 You can't do the things I do!
 Only I can do this!
 I'm better than all of you! Believe it!
 There's a problem, sir!
 Lord Hokage!
 What is it?
 Did that Naruto do something again?
 Yes. He climbed onto the Mountainside Images…
 And he vandalized and graffitied all over them!
 Wait!
 Ha ha…
 Why should I?
 Hey, Naruto!
 How did you suddenly get here, lruka Sensei?
 The question is what are you doing here when you should be in class now?
 Now listen, Naruto.
 You failed the last graduation test and the one before that.
 This is no time to be goofing off, you fool!
 We will have a re-test on the Transformation Jutsu!
 Even those who already passed will take it!
 Whaaaat?!
 Sakura Haruno. Here I go…
 Transform!
 OK!
 I did it!
 Cha!
 Did you see that, Sasuke?
 Next, Sasuke Uchiha.
 Yes.
 O-OK.
 Next, Naruto Uzumaki.
 This is a real pain.
 And it's all your fault.
 Like I care!!
 OK…
 Good luck, Naruto…
 Transform!
 How was it?
 I call it the "Sexy Jutsu"!
 You fool! Stop making idiotic spells!
 Darn…
 Darn…
 I won't let you go home unless you clean that all up.
 I don't care…
 There's nobody home anyway.
 Naruto...
 What is it this time?
 What I meant was…
 If you clean up all that mess, I'll buy you ramen tonight.
 Huh?!
 Yes! I-I will finish it no time!
 Enter: Naruto Uzumaki!
 Naruto.
 Why did you vandalize those faces?
 Don't you know who the Hokage leaders are?
 Of course, I do!
 I know they earned the title Lord Hokage
 because they were the best Ninja of their time, right?
 Especially the Fourth Hokage was a hero
 who saved the village from the nine-tail demon fox.
 Then why did you do that?
 Because I'll become a Hokage myself.
 And I'll be the greatest Hokage of all time!
 So that everyone will finally learn to accept me!
 By the way, Sensei, I have a favor to ask.
 You want another bowl?
 Mmmm…No…
 Can I borrow that Leaf headband for a while?
 This?
 No no!
 This is worn only by those who have graduated from Ninja Academy.
 Tomorrow, you will…
 You're so mean!
 So that's why you took off your goggles…
 Humph... One more bowl please!
 We are now about to begin the graduation test.
 When your name is called, proceed to the next classroom.
 The test is on the Clone Jutsu.
 Oh no…
 Of all the…! That is my weakest Jutsu!
 But still… I will do it no matter what!
 Clone Jutsu!
 Disqualified!
 Iruka Sensei.
 His physical coordination and stamina are excellent.
 And he managed to come up with something.
 Isn't that enough for him to pass?
 Mizuki Sensei... All the others created three or more clones.
 Naruto created just one.
 And it's practically useless. I can't give him a passing mark.
 I 'm a Ninja now!
 You did well. That's my son.
 Congratulations for your graduation.
 I'll cook something good tonight!
 Look at that one.
 It's that boy. I hear he's the only one who failed.
 Serves him right.
 Imagine what would happen if he became a Ninja.
 Isn't that the boy who is actually…
 Hey! We're not supposed to talk about that.
 Iruka. We need to talk later.
 Yes, sir.
 Iruka Sensei isn't trying to be mean to you.
 Then why only me?
 He wants you to become strong from the bottom of his heart.
 You both don't have parents.
 But I really wanted to graduate.
 Heh... I guess I have no choice…
 I'll let you in on a big secret.
 Secret?
 Iruka.
 What is it, Lord Hokage?
 I know how you feel. But…
 Naruto also grew up without knowing the love of his parents…like you.
 Let me go!
 My mom and dad are still out there fighting!
 Wake up, Iruka Sensei!
 What's the matter?
 Come to Lord Hokage's immediately!
 I heard that Naruto… stole the Scroll of Sealing.
 The Scroll of Sealing?!
 Let's see…
 The first Jutsu is… Multi-Shadow Clone Jutsu?
 What?! Already a Jutsu I'm no good at?
 Lord Hokage! We can't forgive him!
 This is not just a prank!
 The Scroll is a dangerous item that the First Hokage sealed!
 Depending on its use…
 It will be a major disaster if it is taken out of the village!
 Yes. Bring Naruto here at once!
 Yes, sir!
 Where did you go…Naruto?
 I will tell everyone in the village about this and eliminate Naruto…
 Then the Scroll of Sealing will be mine!
 Hey you, Naruto!
 You found me..
 And I've only learned one Jutsu.
 He's been practicing the Jutsu…
 until he's become this exhausted and dirty…?
 Listen, listen! I'm gonna show you this amazing Jutsu!
 You're gonna let me graduate if I can do it!
 Isn't it true that I can graduate if I can do one of the Jutsu written here?
 Who told you that?
 Mizuki Sensei. He told me about this scroll, and this place…
 Mizuki did?!
 I'm impressed you found this place.
 I see now…how it is.
 Naruto, give me that scroll.
 Wait, wait… What's going on here?
 Naruto! Never give him that scroll!
 It is a dangerous object that contains forbidden Ninja Jutsu. It was sealed.
 Mizuki used you in order to get it for himself!
 W-Wha--?
 Naruto, Iruka is only afraid of you holding that scroll!
 Huh?
 What are you saying, Mizuki! Don't let him fool you, Naruto!
 I will tell you the truth.
 Idiot! Don't do that!
 After an incident 12 years ago, a rule was created.
 A rule?
 That is, Naruto, a rule everybody but you knows.
 Except me?! 					What is it?
 Stop it, Mizuki!
 The rule forbids anyone from revealing that you are actually the Demon Fox Spirit!
 Huh?
 You are actually the Demon, Nine-Tailed Fox Spirit,
 who killed Iruka's parents and destroyed our village!
 Stop it!
 Everyone has been deceiving you ever since.
 Didn't you find it strange?
 Why everyone hated you so much?
 No! No! No! No! No!
 Naruto…
 Nobody accepts you. That's why Iruka hates you so much!
 Iruka... Naruto grew up without the love of parents.
 Everyone avoids him like the plague after what happened.
 That's why he keeps misbehaving.
 It's the only way for him to get any attention or acknowledgement.
 He pretends to be tough, but inside he is really hurting.
 Die, Naruto!
 Naruto! 					Get down!
 Why…?
 Because you and I are the same.
 After my parents died,
 nobody paid attention to me or gave me any support.
 I wasn't a good student in school.
 I was the class clown… because I wanted people to notice me.
 I couldn't get noticed through excellence, so I kept doing stupid things.
 It was so hard.
 Isn't that right, Naruto?
 You felt so lonely…right? And you suffered inside, right?
 I'm sorry, Naruto….
 If I had been more responsible, maybe you wouldn't have suffered so much.
 Don't make me laugh!
 Iruka has always hated you, ever since you killed his parents!
 He's just saying all that to get the Scroll of Sealing back!
 Naruto!
 Narutoooooo!
 He is not the type of kid who will change his mind.
 He will take revenge against our village using that scroll!
 Didn't you see his eyes? Those are the eyes of a Demon Fox.
 No… Naruto…isn't…like that at all!
 All I want is to kill Naruto and get the scroll.
 I'll take care of you later!
 I-I won't let you…
 Well, well.
 Mizuki has a big mouth!
 Naruto feels worse than he's ever felt.
 He might unleash the power locked up inside him.
 The Scroll of Sealing is now with him.
 There's a slight chance he might actually release
 the Nine-Tailed Fox Spirit sealed inside him!
 If that happens…
 I've found him!
 Naruto!
 Everything that Mizuki said was a lie!
 Give me that scroll, quick! Mizuki is after the scroll!
 It can't be…
 Why is it, Naruto?
 How…
 did you know I wasn't Iruka…?
 Because I'm Iruka.
 I see.
 What's in it for you to protect the one who killed your family?
 I'm not gonna let a stupid idiot like you get that scroll!
 You're the idiot. Naruto is the same as me.
 Same?
 Anyone can do whatever he wants once he has the scroll.
 There is no way that that monster…
 that Fox Spirit, won't take advantage of the power of that scroll!
 You're right…
 I guess it was true all along!
 See, Iruka Sensei never really cared for me at all!
 ...if he was the Demon Fox Spirit.
 But Naruto is different!
 I know that he is an exceptional student.
 He works very hard,
 and he's single-minded and clumsy at the same time.
 No one accepts him, but he knows the meaning of human suffering.
 He is not the Demon Fox Spirit.
 He's Naruto Uzumaki of the Village Hidden in the Leaves!
 You are so gullible. 					lruka!
 I was gonna take you down later, but I have changed my mind.
 Die!
 I guess this is the end for me…
 Naruto?!
 You surprised me there, freak.
 If you ever lay a hand on Iruka Sensei, I'll kill you!
 Shut up! I can take care of a kid like you with a single blow!
 Why don't you try then? I'll strike you back a thousand-fold!
 Let's see you try! Show me what you can do, Demon Fox!
 Shadow Clone Jutsu!
 Naruto! You've…
 Those aren't just images but actual clones! That's an advanced Ninjutsu!
 What's this…?
 What's the matter? 					C'mon!
 Weren't you gonna get me with one blow? Here!
 In that case… I'll come to you.
 I kinda got carried away. lruka Sensei, are you okay?
 Yeah.
 He's really something.
 Maybe it is true.
 Maybe he will surpass all the Hokage leaders…
 Naruto, come over here. I'd like to give you something.
 Has anyone found Naruto yet?
 No.
 Darn, this is going to be bad…
 There's no need to worry anymore.
 Lord Hokage!
 He'll be back soon.
 Sensei, how much longer?
 OK, you may open your eyes now.
 Congratulations…on your graduation.
 In celebration, we'll have ramen tonight!
 Iruka Sensei!
 That hurts!
 Naruto…
 I was going to lecture to you...
 that the road gets more difficult now that you're a Ninja.
 But I guess I'll just wait to tell you that until we get to the ramen stand…
 W-What do you want, you little shrimp? Quit following me!
 You're smaller than me and
 you're saying that you're gonna become the Fifth Hokage?
 I don't care if you are the 3rd Hokage's grandson or not.
 It's not that easy to be a Hokage!
 If you want it that bad, you're gonna have to beat me first!
 Next episode:  "My Name Is Konohamaru!"
 Watch my outstanding performance!

In [79]:
script_sentences = sent_tokenize(script)
script_sentences[:3]
print(len(script_sentences))

299

In [ ]:
sentence_batch_size=20
script_batches = []
for index in range(0,len(script_sentences),sentence_batch_size):
    sent = " ".join(script_sentences[index:index+sentence_batch_size])
    script_batches.append(sent)
print(len(script_batches))

15

In [83]:
script_batches[:2]

["A long time ago, a powerful demon fox appeared with nine tails. With its powerful tails,\n it could smash mountains and create tidal waves. A band of Ninjas rose to defend their village from attack. We have to wait until the Fourth Hokage gets here! We can't let it get any closer to our village! One great Ninja was able to imprison the monster,\n but died in the process. This Ninja was known as… the Fourth Hokage. Naruto! Why did you do such a thing?! You're really gonna get it this time! I don't care! You know your problem? You can't do the things I do! Only I can do this! I'm better than all of you! Believe it! There's a problem, sir! Lord Hokage! What is it? Did that Naruto do something again?",
 'Yes. He climbed onto the Mountainside Images…\n And he vandalized and graffitied all over them! Wait! Ha ha…\n Why should I? Hey, Naruto! How did you suddenly get here, lruka Sensei? The question is what are you doing here when you should be in class now? Now listen, Naruto. You failed the last graduation test and the one before that. This is no time to be goofing off, you fool! We will have a re-test on the Transformation Jutsu! Even those who already passed will take it! Whaaaat?! Sakura Haruno. Here I go…\n Transform! OK! I did it! Cha! Did you see that, Sasuke? Next, Sasuke Uchiha.']

In [84]:
theme_output = theme_classifier(
    script_batches[:2],
    theme_list,
    multi_label=True
)

In [85]:
theme_output

[{'sequence': "A long time ago, a powerful demon fox appeared with nine tails. With its powerful tails,\n it could smash mountains and create tidal waves. A band of Ninjas rose to defend their village from attack. We have to wait until the Fourth Hokage gets here! We can't let it get any closer to our village! One great Ninja was able to imprison the monster,\n but died in the process. This Ninja was known as… the Fourth Hokage. Naruto! Why did you do such a thing?! You're really gonna get it this time! I don't care! You know your problem? You can't do the things I do! Only I can do this! I'm better than all of you! Believe it! There's a problem, sir! Lord Hokage! What is it? Did that Naruto do something again?",
  'labels': ['dialogue',
   'betrayal',
   'battle',
   'sacrifice',
   'self development',
   'hope',
   'friendship',
   'love'],
  'scores': [0.9800742268562317,
   0.9396902322769165,
   0.8546884059906006,
   0.7349813580513,
   0.7284974455833435,
   0.19909794628620148,
   0.05922335758805275,
   0.04026177525520325]},
 {'sequence': 'Yes. He climbed onto the Mountainside Images…\n And he vandalized and graffitied all over them! Wait! Ha ha…\n Why should I? Hey, Naruto! How did you suddenly get here, lruka Sensei? The question is what are you doing here when you should be in class now? Now listen, Naruto. You failed the last graduation test and the one before that. This is no time to be goofing off, you fool! We will have a re-test on the Transformation Jutsu! Even those who already passed will take it! Whaaaat?! Sakura Haruno. Here I go…\n Transform! OK! I did it! Cha! Did you see that, Sasuke? Next, Sasuke Uchiha.',
  'labels': ['dialogue',
   'self development',
   'battle',
   'betrayal',
   'sacrifice',
   'hope',
   'friendship',
   'love'],
  'scores': [0.9370126128196716,
   0.8678207993507385,
   0.6581322550773621,
   0.645726203918457,
   0.6258843541145325,
   0.20423975586891174,
   0.08603321015834808,
   0.028020622208714485]}]

In [ ]:
themes  = {}

for output in theme_output:
    for label, score in zip(output['labels'] , output["scores"]):
        if label not in themes:
            themes[label] = []
        themes[label].append(score)
themes

{'dialogue': [0.9800742268562317, 0.9370126128196716],
 'betrayal': [0.9396902322769165, 0.645726203918457],
 'battle': [0.8546884059906006, 0.6581322550773621],
 'sacrifice': [0.7349813580513, 0.6258843541145325],
 'self development': [0.7284974455833435, 0.8678207993507385],
 'hope': [0.19909794628620148, 0.20423975586891174],
 'friendship': [0.05922335758805275, 0.08603321015834808],
 'love': [0.04026177525520325, 0.028020622208714485]}

In [92]:
def get_themes_inference(script):
    script_sentences = sent_tokenize(script)

    # Batch Sentence
    sentence_batch_size=20
    script_batches = []
    for index in range(0,len(script_sentences),sentence_batch_size):
        sent = " ".join(script_sentences[index:index+sentence_batch_size])
        script_batches.append(sent)
    
    # Run Model
    theme_output = theme_classifier(
        script_batches[:2],
        theme_list,
        multi_label=True
    )

    # Wrangle Output 
    themes = {}
    for output in theme_output:
        for label,score in zip(output['labels'],output['scores']):
            if label not in themes:
                themes[label] = []
            themes[label].append(score)
    

    themes = {key: np.mean(np.array(value)) for key,value in themes.items()}
    print(themes)
    return themes

In [89]:
df = df.head(2)

In [90]:
df

   epsiode_num                                             script
0            1  A long time ago, a powerful demon fox appeared...
1            2  C'mon!\n Running like a fugitive,\n Being chas...

In [93]:
output_themes = df['script'].apply(get_themes_inference)

{'dialogue': np.float64(0.9585434198379517), 'betrayal': np.float64(0.7927082180976868), 'battle': np.float64(0.7564103305339813), 'sacrifice': np.float64(0.6804328560829163), 'self development': np.float64(0.798159122467041), 'hope': np.float64(0.2016688510775566), 'friendship': np.float64(0.07262828387320042), 'love': np.float64(0.034141198731958866)}
{'dialogue': np.float64(0.9606060683727264), 'sacrifice': np.float64(0.5707033574581146), 'self development': np.float64(0.4828104078769684), 'battle': np.float64(0.6848459839820862), 'love': np.float64(0.17326094000600278), 'hope': np.float64(0.1545334211550653), 'friendship': np.float64(0.04626084305346012), 'betrayal': np.float64(0.42994374223053455)}

In [96]:
theme_df = pd.DataFrame(output_themes.to_list())

In [98]:
df[theme_df.columns] = theme_df
df

C:\Users\shawa\AppData\Local\Temp\ipykernel_19316\3417989627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[theme_df.columns] = theme_df

,epsiode_num,script,dialogue,betrayal,battle,sacrifice,self development,hope,friendship,love
0,1,"A long time ago, a powerful demon fox appeared...",0.958543,0.792708,0.756410,0.680433,0.798159,0.201669,0.072628,0.034141
1,2,"C'mon!\n Running like a fugitive,\n Being chas...",0.960606,0.429944,0.684846,0.570703,0.482810,0.154533,0.046261,0.173261